name: AQI Prediction Pipeline

on:
  schedule: # runs 15 times a day
    - cron: "0 0,8,16 * * *"   # Runs at 00:00, 08:00, 16:00
    - cron: "36 1,9,17 * * *"  # Runs at 01:36, 09:36, 17:36
    - cron: "12 3,11,19 * * *" # Runs at 03:12, 11:12, 19:12
    - cron: "48 4,12,20 * * *" # Runs at 04:48, 12:48, 20:48
    - cron: "24 6,14,22 * * *" # Runs at 06:24, 14:24, 22:24
    - cron: "0 0 * * 0"        # Runs at midnight on Sunday

  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run feature script
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python features_script.py

  training_pipeline:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * 0' || github.event_name == 'workflow_dispatch'  # Run on Sunday at midnight OR manual trigger
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python training_script.py
