name: AQI Prediction Pipeline

on:
  schedule:
    - cron: "0 * * * *"  # Runs at the start of every hour (for feature_pipeline)
    - cron: "0 0 * * 0"  # Runs at midnight UTC on Sunday (for training_pipeline)
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run feature script
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python features_script.py

  training_pipeline:
    runs-on: ubuntu-latest
    if: always()  # Ensures job is evaluated every time the workflow runs
    steps:
      - name: Check if triggered by schedule or manual dispatch
        run: |
          if [ -z "${{ github.event.schedule }}" ] && [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            echo "Not triggered by schedule or manual dispatch, skipping..."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python training_script.py
